version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

    labels:
      - "dependencies"
      - "ci"

    commit-message:
      prefix: "ci"

  - package-ecosystem: "docker"
    directory: "/examples/smoke-api"
    schedule:
      interval: "weekly"
      day: "monday"

    labels:
      - "dependencies"
      - "docker"

    commit-message:
      prefix: "build"
